#!/bin/bash

scriptdir="$(dirname ${BASH_SOURCE[0]})" || exit 1
cd "$scriptdir" || exit 1
source build.bash || exit 1

qs_demo_launcher\
 --list launcherList\
 --title "some Open Scene Graph example programs"
